deco-sites/otica-isabela

accounts/configStore.ts
live.gen.ts
packs/accounts/configStore.ts
schemas.gen.json

Adding configStore account

---

components/product/ProductCard.tsx
components/product/ProductShelf.tsx
components/product/ToExperimentButton.tsx
islands/ProductCard.tsx
islands/ToExperimentButton.tsx
live.gen.ts
packs/types.ts
sdk/getVariantColors.ts

Fixing product card rendering on client side.
Now it's rendering on server-side and only the ToExperimentButton is rendering on client-side.
Go to any page that has the ProductCard and you'll be able to interact it with accordingly.

prevent the entire product-card to be loaded on client-side

---

packs/loaders/cart.ts
packs/loaders/productDetails.ts
packs/loaders/productList.ts
packs/loaders/productListiningPage.ts
packs/loaders/session.ts
packs/loaders/suggestions.ts
packs/utils/transform.ts

Now, PLP loader works properly with props

fix(packs): plp loader now work with props

---

components/ui/Newsletter.tsx
loaders/store/newsletter.ts
manifest.gen.ts
packs/loaders/newsletter.ts
packs/types.ts
packs/utils/paths.ts

Add newsletter loader added; Its already working properly
Try to use the newsletter in the end of the pages or in [store/newsletter.ts](https://deco.cx/admin/sites/otica-isabela/blocks/?returnLabel=Blocos&returnUrl=%2Fadmin%2Fsites%2Fotica-isabela%2Flibrary&ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9vdGljYS1pc2FiZWxhL2xvYWRlcnMvc3RvcmUvbmV3c2xldHRlci50cw%3D%3D&type=store)
(In this last i forced an error in the url path to test exceptions)

feat(packs): add newsletter added

---

components/product/ProductDetails.tsx
manifest.gen.ts

Bug fixed at visited products shelf: Now, when a pdp do not exists, his id is not registered in cookie

fix(packs): visited product self bug fixed

---

manifest.gen.ts
packs/utils/transform.ts

Now, memberLevel is being returned properly.
https://deco.cx/admin/sites/otica-isabela/blocks/productTestimonials?returnLabel=Blocos&returnUrl=%2Fadmin%2Fsites%2Fotica-isabela%2Flibrary&revisionId=8f01717e-01b1-4ef8-8b47-9b7bffa76237&sidebarMode=edit&tab=0

fix(packs): now, memberLevel are returned properly

---

manifest.gen.ts
packs/types.ts
packs/utils/transform.ts

Videos are now being returned properly by the pdp loader
Go to [product/productDetails.ts](https://deco.cx/admin/sites/otica-isabela/blocks/?returnLabel=Blocos&returnUrl=%2Fadmin%2Fsites%2Fotica-isabela%2Flibrary&ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9vdGljYS1pc2FiZWxhL2xvYWRlcnMvcHJvZHVjdC9wcm9kdWN0RGV0YWlscy50cw%3D%3D&type=product) in deco panel an type an valid slug with a video

fix(packs): now, videos are returned properly

---

components/product/product-details/Details.tsx

Add video renderer within PDP
Go to any PDP that has a product with video.

add video renderer within PDP

---

manifest.gen.ts
packs/actions/cart/addItem.ts
packs/actions/wishlist/addItem.ts
packs/actions/wishlist/removeItem.ts
packs/loaders/cart.ts
packs/loaders/newsletter.ts
packs/loaders/productDetails.ts
packs/loaders/productList.ts
packs/loaders/productListiningPage.ts
packs/loaders/session.ts
packs/loaders/suggestions.ts
packs/loaders/testimonials.ts
packs/loaders/wishlist.ts
packs/types.ts

Decocache now added in the loaders that it should be:
ProductDetails;
ProductList - Except when returning promotional itens
ProductListiningPage - Just in category pages
Suggestions
Testimonials
BTW, the admin form of the loaders was translated.

feat(packs): now, decocache works properly in some loaders

---

components/product/product-details/Details.tsx

When the user clicks on the rating stars Mobile/Desktop the user will be scrolled to the Product Review Section.
Go to any PDP that has Review and click in the rating stars.

make stars scroll to product review when clicked

---

packs/constants.ts

Login and check the image and name of the user logged in appearing in the header.

fix name and image of user logged in

---

components/product/ChooseLensButton.tsx
components/product/product-details/ProductInfo.tsx
components/ui/CartModalMobile.tsx
sdk/useAddToCart.ts

add preventDefault on add-to-cart to prevent error on firefox

---

components/footer/FirstBlock.tsx
components/header/Navbar.tsx
components/product/ProductCard.tsx
components/product/product-details/Details.tsx
components/product/product-details/ProductInfo.tsx
components/product/product-details/Reviews/Feedback.tsx
components/product/product-details/ShareButton.tsx
components/product/product-details/SpecsMobile.tsx
components/search/Searchbar.tsx
components/ui/TestimonialItem.tsx
sections/Content/Faq.tsx

| Mobile | Desktop |
|----------|----------|
| ![image](https://github.com/deco-sites/otica-isabela/assets/47363947/d87fcf5b-54ed-493e-ae55-0c8fa0e644b8) | ![image](https://github.com/deco-sites/otica-isabela/assets/47363947/cc45778b-6766-40f6-af7b-9901d14588df) |
| Mobile | Desktop |
|----------|----------|
| ![image](https://github.com/deco-sites/otica-isabela/assets/47363947/d87fcf5b-54ed-493e-ae55-0c8fa0e644b8) | ![image](https://github.com/deco-sites/otica-isabela/assets/47363947/cc45778b-6766-40f6-af7b-9901d14588df) |
| Mobile | Desktop |
|----------|----------|
| <img width="993" alt="image" src="https://github.com/deco-sites/otica-isabela/assets/47363947/2f214f6c-8e73-4e26-a2fa-4aa9d2e23cbd"> | <img width="982" alt="image" …

perform some adjustments for accessbility

---

components/header/IconLoginLink.tsx

style: hidden login icon in mobile

---

components/product/ProductDetails.tsx
components/product/product-details/Details.tsx

style: decrease padding y axis

---

components/header/IconNavigation.tsx
components/search/SearchResult.tsx

feat: add editable not found alert to searchresults props

---

components/search/SearchResult.tsx

fix: pageName on searchResult

---

components/header/Ajuda.tsx
components/header/IconLoginLink.tsx
components/header/Menu.tsx
components/ui/Carrossel.tsx
components/ui/Slider.tsx

fix: text login & slider button

---

components/ui/Carrossel.tsx

fix: mobile height carrossel

---

components/header/Navbar.tsx

fix: adjust url wishlist

---

components/header/NavItem.tsx

feat: size image menu desktop

---

.deco/blocks/Home.json
.deco/blocks/New%20Carrossel.json
.deco/blocks/site.json
components/header/Header.tsx
components/product/ProductDetails.tsx
components/product/SingleProductShelf.tsx
components/product/product-details/ProductInfo.tsx
components/search/SearchResult.tsx
components/ui/AntiBenefits.tsx
components/ui/AntiOptions.tsx
components/ui/ContactUs.tsx
components/ui/DeferredIframe.tsx
components/ui/Institutional.tsx
components/ui/Presentation.tsx
components/ui/SideMenuNavigation/SideMenuNavigation.tsx
components/ui/SimpleCard.tsx
components/ui/Tutorial/Tutorial.tsx
deno.json
fresh.config.ts
routes/live/invoke/_middleware.tsx

fix: imports after update

---

components/header/Menu.tsx
components/product/ProductCard.tsx
components/ui/CategoryMenu.tsx
static/tailwind.css

fix: menu mobile dropdown & categorymenu hidden

---

components/product/AddToCartButton.tsx
components/product/product-details/ProductInfo.tsx
components/ui/CartModalMobile.tsx
static/tailwind.css

fix: text add to cart on pdp

---

components/product/ProductCard.tsx
components/product/ProductDetails.tsx
components/product/product-details/ProductInfo.tsx

fix: flag pdp

---

components/product/ProductDetails.tsx
components/product/product-details/Details.tsx

fix: promotion mobile

---

components/product/product-details/Reviews/Feedback.tsx

fix: change feedback testimonials rating texts

---

.deco/blocks/Home.json
components/ui/TestimonialItem.tsx
sections/Images/CategoriesShelf.tsx
static/tailwind.css

fix: two components

---

components/ui/TestimonialItem.tsx

fix: height testimonial

---

deno.json
fresh.config.ts

[Chore] - bump deps

---

components/product/product-details/SpecsDesktop.tsx
components/ui/Carrossel.tsx
static/tailwind.css

fix: bannercarrossel home

---

.deco/blocks/Home.json
.deco/blocks/New%20Carrossel.json
components/ui/Carrossel.tsx
components/ui/Section.tsx
sections/Content/About.tsx
sections/Content/Faq.tsx
sections/Content/RichText.tsx
sections/Content/Testimonials.tsx
sections/Images/CategoriesShelf.tsx
sections/Newsletter/Newsletter.tsx
sections/Product/ProductBannerShelf.tsx
sections/Product/ProductBestDailyOffers.tsx
sections/Product/VisitedProductShelf.tsx
static/tailwind.css

perf: images and active async render section home

---

components/ui/Carrossel.tsx
sections/Footer/Footer2.tsx
static/tailwind.css

fix: images priority

---

.deco/blocks/Home.json
components/ui/Carrossel.tsx

perf: images priority again

---

components/ui/Carrossel.tsx
components/ui/WhatsApp.tsx

fix: preload

---

components/ui/Carrossel.tsx
static/tailwind.css

feat: border radius banner carrossel

---

components/product/product-details/Details.tsx

fix: remove accessoriesimagepath

---

components/ui/Carrossel.tsx
static/tailwind.css

fix: carrossel mobile src

---

.deco/blocks/Categories.json
packs/actions/cart/addItem.ts

fix: remove clienttoken verification

---

packs/loaders/productDetails.ts
static/tailwind.css

feat: change method get to post on productdetails
